<?php

$users =
[
    [
        'user_id'           => '0',
        'email'             => 'admin@example.com',
        'username'          => 'admin',
        'password'          => 'admin',
        'firstname'         => 'admin',
        'lastname'          => 'admin',
        'role'              => 'sysadmin',
        'organisation_id'   => '',
    ],
    [
        'user_id'           => '1',
        'email'             => 'lucasvdvegt@gmail.com',
        'username'          => 'LucasV',
        'password'          => '123',
        'firstname'         => 'Lucas',
        'lastname'          => 'van der Vegt',
        'role'              => 'default',
        'organisation_id'   => 'reflax',
    ],
    [
        'user_id'           => '2',
        'email'             => 'jeffrey19@example.com',
        'username'          => 'Jeffrey',
        'password'          => '123',
        'firstname'         => 'Jeffrey',
        'lastname'          => 'van der Vegt',
        'role'              => 'admin',
        'organisation_id'   => 'reflax',
    ],
    [
        'user_id'           => '3',
        'email'             => 'daveg@example.com',
        'username'          => 'DaveG',
        'password'          => '123',
        'firstname'         => 'Dave',
        'lastname'          => 'Grohl',
        'role'              => 'moderator',
        'organisation_id'   => 'foofighters',
    ],
    [
        'user_id'           => '4',
        'email'             => 'chris@example.com',
        'username'          => 'ChrisS',
        'password'          => '123',
        'firstname'         => 'Chris',
        'lastname'          => 'Shiflett',
        'role'              => 'default',
        'organisation_id'   => 'foofighters',
    ],
    [
        'user_id'           => '5',
        'email'             => 'chris@example.com',
        'username'          => 'ChrisS',
        'password'          => '123',
        'firstname'         => 'Chris',
        'lastname'          => 'Shiflett',
        'role'              => 'default',
        'organisation_id'   => 'foofighters',
    ],
    [
        'user_id'           => '5',
        'email'             => 'patpat@example.com',
        'username'          => 'SmearP',
        'password'          => '123',
        'firstname'         => 'Pat',
        'lastname'          => 'Smear',
        'role'              => 'default',
        'organisation_id'   => 'foofighters',
    ],
    [
        'user_id'           => '6',
        'email'             => 'natemp@example.com',
        'username'          => 'Natem',
        'password'          => '123',
        'firstname'         => 'Nate',
        'lastname'          => 'Mendal',
        'role'              => 'default',
        'organisation_id'   => 'foofighters',
    ],
    [
        'user_id'           => '7',
        'email'             => 'natemp@example.com',
        'username'          => 'Natem',
        'password'          => '123',
        'firstname'         => 'Taylor',
        'lastname'          => 'Hawkins',
        'role'              => 'default',
        'organisation_id'   => 'foofighters',
    ],
    [
        'user_id'           => '8',
        'email'             => 'franzzzz@example.com',
        'username'          => 'franzzzz',
        'password'          => '123',
        'firstname'         => 'Franz',
        'lastname'          => 'Stahl',
        'role'              => 'guest',
        'organisation_id'   => 'foofighters',
    ],
];

?>